// Renders an already-generated compliance memo (see /api/compliance-memo)
// into a real one-page PDF -- pdfkit is pure JS (no native deps, no
// Chromium), so it installs and runs cleanly in the Databricks Apps Node
// runtime. Deliberately renders the SAME memo object already shown in the
// chat card rather than re-running the SQL + ai_query pipeline: guarantees
// the PDF matches exactly what the user saw on screen, and doesn't burn a
// second (non-deterministic) model call just to produce a document.

import PDFDocument from "pdfkit";

const RISK_COLORS = { Low: "#2e7d32", Medium: "#b8860b", High: "#c62828" };

function section(doc, title, body, { compact = false } = {}) {
  if (!body) return;
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#111").text(title);
  doc.moveDown(0.15);
  doc.fontSize(9.5).font("Helvetica").fillColor("#222").text(body, { lineGap: 1 });
  doc.moveDown(compact ? 0.5 : 0.7);
}

export function renderMemoPdf(memo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 42, size: "LETTER", bufferPages: true });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Letterhead
    doc.fillColor("#E50914").font("Helvetica-Bold").fontSize(20).text("DATAFLIX");
    doc.fillColor("#555").font("Helvetica").fontSize(9).text("Content Compliance & Licensing Memo");
    doc.moveDown(0.4);
    doc.strokeColor("#E50914").lineWidth(1.5).moveTo(42, doc.y).lineTo(570, doc.y).stroke();
    doc.moveDown(0.6);

    // Header block
    doc.fillColor("#111").font("Helvetica-Bold").fontSize(15).text(
      `${memo.titleName}${memo.region ? ` — ${memo.region}` : " — All Licensed Regions"}`
    );
    doc.fillColor("#777").font("Helvetica").fontSize(8).text(
      `Generated ${new Date(memo.generatedAt || Date.now()).toLocaleString()}`
    );
    if (memo.riskLevel) {
      doc.moveDown(0.2);
      doc.fillColor(RISK_COLORS[memo.riskLevel] || "#333").font("Helvetica-Bold").fontSize(10).text(
        `Risk Level: ${memo.riskLevel}`
      );
    }
    doc.moveDown(0.5);

    section(doc, "License Summary", memo.licenseSummary, { compact: true });
    section(doc, "Certification", memo.certificationNote, { compact: true });

    if (memo.regulatoryConsiderations?.length > 0) {
      doc.fillColor("#111").font("Helvetica-Bold").fontSize(11).text("Regulatory Considerations");
      // Plain text, not a unicode checkmark -- pdfkit's built-in Helvetica
      // AFM font only covers WinAnsi encoding and silently mis-renders
      // glyphs like U+2713 as an unrelated substitute character.
      doc.fillColor("#2e7d32").font("Helvetica-Oblique").fontSize(7.5).text(
        "Verified: sourced only from real, official regulatory documents"
      );
      doc.moveDown(0.2);
      for (const c of memo.regulatoryConsiderations) {
        doc.fillColor("#222").font("Helvetica").fontSize(9.5).text(`• ${c.point}`, { lineGap: 1 });
        doc.fillColor("#888").font("Helvetica-Oblique").fontSize(8).text(`   Source: ${c.source}`);
        doc.moveDown(0.2);
      }
      doc.moveDown(0.4);
    }

    section(doc, "Recommendation", memo.recommendation, { compact: true });

    doc.fontSize(7).fillColor("#999").font("Helvetica").text(
      "Generated by Dataflix from real licensing/certification system records and real, official regulatory documents. Internal review use only -- not legal advice.",
      42,
      730,
      { width: 528, align: "center" }
    );

    doc.end();
  });
}
