"""
Casting Recommendation feature — chunk the 40 real actor-profile PDFs
(generated by 06_generate_actor_profiles.py) and write local parquet extracts
for dataflix.casting.actor_registry / actor_profile_chunks. Same chunking
approach as notebooks/02_build_document_corpus_and_ocr.py (word-count
approximation of ~500 tokens/~50 overlap).

Usage:
  .venv/bin/python notebooks/07_load_actor_profile_corpus.py
"""

import json
import re
from pathlib import Path

import pandas as pd
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
PDF_DIR = ROOT / "data" / "raw" / "docs" / "actor_profiles" / "pdf"
OUT_DIR = ROOT / "data" / "raw" / "docs" / "actor_profiles"

WORDS_PER_CHUNK = 375
OVERLAP_WORDS = 40


def extract_pages(pdf_path: Path) -> list[str]:
    reader = PdfReader(str(pdf_path))
    return [page.extract_text() or "" for page in reader.pages]


def chunk_pages(pages: list[str]) -> list[dict]:
    words_with_page = []
    for page_num, text in enumerate(pages, start=1):
        for w in re.split(r"\s+", text.strip()):
            if w:
                words_with_page.append((w, page_num))

    chunks = []
    i = 0
    n = len(words_with_page)
    step = WORDS_PER_CHUNK - OVERLAP_WORDS
    while i < n:
        window = words_with_page[i : i + WORDS_PER_CHUNK]
        if not window:
            break
        chunk_text = " ".join(w for w, _ in window)
        page_num = window[0][1]
        chunks.append({"chunk_text": chunk_text, "page_num": page_num})
        if i + WORDS_PER_CHUNK >= n:
            break
        i += step
    return chunks


def main():
    manifest = json.loads((ROOT / "data" / "raw" / "actor_profiles_manifest.json").read_text())

    registry_rows = []
    chunk_rows = []

    for row in manifest:
        actor_id = int(row["actor_id"])
        fname = row["filename"]
        pdf_path = PDF_DIR / fname
        if not pdf_path.exists():
            print(f"  SKIP missing {fname}")
            continue

        pages = extract_pages(pdf_path)
        chunks = chunk_pages(pages)
        source_path = f"/Volumes/dataflix/casting/raw_documents/actor_profiles/{fname}"

        registry_rows.append(
            {
                "actor_id": actor_id,
                "actor_name": row["actor_name"],
                "industry": row["industry"],
                "source_path": source_path,
            }
        )
        for idx, c in enumerate(chunks):
            chunk_rows.append(
                {
                    "chunk_id": f"actor_{actor_id}_chunk{idx:03d}",
                    "actor_id": actor_id,
                    "actor_name": row["actor_name"],
                    "industry": row["industry"],
                    "source_path": source_path,
                    "chunk_text": c["chunk_text"],
                    "page_num": c["page_num"],
                }
            )
        print(f"{fname}: {len(pages)} pages -> {len(chunks)} chunks")

    registry = pd.DataFrame(registry_rows)
    chunks_df = pd.DataFrame(chunk_rows)

    registry.to_parquet(OUT_DIR / "actor_registry.parquet", index=False)
    chunks_df.to_parquet(OUT_DIR / "actor_profile_chunks.parquet", index=False)

    print(f"\nactor_registry: {len(registry)} rows -> {OUT_DIR / 'actor_registry.parquet'}")
    print(f"actor_profile_chunks: {len(chunks_df)} rows -> {OUT_DIR / 'actor_profile_chunks.parquet'}")


if __name__ == "__main__":
    main()
